filebeat.inputs:
- type: filestream
  id: my-springboot-json-logs
  paths:
    - /app/logs/app.log
  parsers:
    - ndjson:
        keys_under_root: true
        add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

